CREATE DATABASE IF NOT EXISTS nids_db;
USE nids_db;

CREATE TABLE USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(45) UNIQUE NOT NULL,
    role VARCHAR(30),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE RULES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    RULE_NAME VARCHAR(100) NOT NULL,
    CONDITION TEXT NOT NULL,
    ACTIVE BOOLEAN DEFAULT TRUE,
    SEVERITY ENUM('LOW', 'MEDIUM', 'HIGH') NOT NULL
);

CREATE TABLE NETWORK_LOGS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT,
    source_ip VARCHAR(45),
    destination_ip VARCHAR(45),
    source_port INT,
    destination_port INT,
    protocol VARCHAR(10),
    packet_size INT,
    flags VARCHAR(20),
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_suspicious BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TABLE ALERTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    MESSAGE TEXT,
    RULE_ID INT,
    LOG_ID INT,
    ALERT_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RULE_ID) REFERENCES RULES(id),
    FOREIGN KEY (LOG_ID) REFERENCES NETWORK_LOGS(id)
);
